# Generated by Django 4.0.10 on 2023-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='image_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='twit',
            name='body',
            field=models.TextField(max_length=140),
        ),
    ]
