# Generated by Django 4.0.10 on 2023-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter your date of birth in YYYY/MM/DD format.', null=True),
        ),
    ]
